### ISSUE TITLE
Gateway Issue

### ISSUE THREAD

**Issue by DontEatOreo** [ProjectCuteAndFunny/CunnyApi#5]
Entering invalid tag/s for **Danbooru**, **Konachan** or **Yandere** causes the server to take too long to respond and ending up with ``502 Bad Gateway`` or ``504 Gateway Time-out`` after long time of waiting. 

While **Gelbooru** and **Safebooru** return ``500 Internal Server Error`` on invalid tag/s.

**Comment by GermanBread** [comment]
should be fixed in dd30e41e1a470bd31eb4bce2c5b9b7e62044aee8
